# Generated by Django 3.1.7 on 2021-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210324_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='save_just_for_you',
            field=models.BooleanField(default=False),
        ),
    ]
