# Generated by Django 3.1.7 on 2021-03-31 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_save_just_for_you'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='save_just_for_you',
            new_name='save_for_you',
        ),
    ]
